USE [master]
GO

/****** Object:  Database [phones]    Script Date: 21.10.2020 22:25:18 ******/
CREATE DATABASE [phones]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'phones', FILENAME = N'A:\MSqlExpress\MSSQL14.SQLEXPRESS\MSSQL\DATA\phones.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'phones_log', FILENAME = N'A:\MSqlExpress\MSSQL14.SQLEXPRESS\MSSQL\DATA\phones_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [phones].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [phones] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [phones] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [phones] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [phones] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [phones] SET ARITHABORT OFF 
GO

ALTER DATABASE [phones] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [phones] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [phones] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [phones] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [phones] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [phones] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [phones] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [phones] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [phones] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [phones] SET  DISABLE_BROKER 
GO

ALTER DATABASE [phones] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [phones] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [phones] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [phones] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [phones] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [phones] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [phones] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [phones] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [phones] SET  MULTI_USER 
GO

ALTER DATABASE [phones] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [phones] SET DB_CHAINING OFF 
GO

ALTER DATABASE [phones] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [phones] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [phones] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [phones] SET QUERY_STORE = OFF
GO

ALTER DATABASE [phones] SET  READ_WRITE 
GO

